### ISSUE TITLE
Permission denied The exception occurred while attempting to log [Laravel]

### ISSUE THREAD

**Issue by sanjayojha** [sfx101/docker-stacks#139] opened 2023-04-14 09:57 UTC
For some reason, Laravel can not write in stroage log. I am getting following error:
```log
The stream or file "/var/www/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log:
```
Using Windows with WSL2.

**Comment by nabad600** [comment] 2023-04-14 11:03
Hi @sanjayojha, 
You can change the directory permission through the console, please below the details
![image](https://user-images.githubusercontent.com/67466982/232026117-e72e2cf9-2c97-4c4d-9eae-b61d32196e7a.png)
                                                                      **Click Shell**
![image](https://user-images.githubusercontent.com/67466982/232026355-3b33a325-85ec-4fed-985c-57762c6b4705.png)
                                                                      **Click LARAVEL container**
![image](https://user-images.githubusercontent.com/67466982/232026555-732eae02-e445-40f0-8148-ecd7beb56512.png)
                                                                      open console

![image](https://user-images.githubusercontent.com/67466982/232026765-efeabd4e-530a-4fe5-b117-037d17ec8ac7.png)
                                                Run the command `sudo chmod 777 storage`

Hope the issue is resolved.

**Comment by nabad600** [comment] 2023-04-18 07:46
Hi @sanjayojha 
Hope the issue is resolved, I'm closing this ticket as you created a separate ticket with a new issue.
we'd be happy to help

**Closed as completed by nabad600** 2023-04-18 07:46 UTC
