### ISSUE TITLE
DECK App status indicator does not work

### ISSUE THREAD

**Issue by solidterre** [sfx101/docker-stacks#136] opened 2023-04-06 09:33 UTC
Computer: Apple MacBook Pro 14" - Apple M1 Pro (Sillicon) - MacOS 13.2.1 (22D68)

Something which has been confusing me for some time now: the container status indicator does not seem to work for me.

As you will see in the screenshots, it seems Deck App does not register that the container has successfully launched and is running. Which leaves the user struggling to know if the container actually is or isn't running or whether there is or isn't an issue ongoing.

![Capture d’écran 2023-04-06 à 11 36 17](https://user-images.githubusercontent.com/8171049/230338018-3b630ff1-4d0c-430f-93a1-aaaaa2c0f286.png)

![Capture d’écran 2023-04-06 à 11 00 06](https://user-images.githubusercontent.com/8171049/230338025-5441a19f-e844-420e-a5e9-410817f03330.png)

**Comment by nabad600** [comment] 2023-04-06 09:53
Hi @rakami-solid, I appreciate for sharing your thoughts. We are trying to replicate the issue in our environment, and, hence, will try to resolve the issue ASAP.
And could you see if the "Decker App" has been reloaded?
We'd be glad to assist.

**Comment by nabad600** [comment] 2023-04-10 08:43
Hi @rakami-solid, can you share your "DECK-APP" Setting?
![image](https://user-images.githubusercontent.com/67466982/230863774-8dfe4064-4482-4fd2-8a54-db09540cf05a.png)
**For reference** 
https://www.loom.com/share/3eb0d766cbb5497887a743f5eec3d6a5
Please uncheck "Remote engine" when using "Docker desktop"
I hope the issue is resolved. Appreciate your feedback here. Let us know of any issues, we'd be happy to help.

**Comment by nabad600** [comment] 2023-04-12 04:34
Hi @rakami-solid,
We may need to close this ticket in the next 24 hours. So, I request you inform us about the status of your query.
Let us know of any issues, we'd be happy to help.

**Closed as completed** 2023-04-13 04:02 UTC
Labels: bug
